export const AUTHORIZATION = 'AUTHORIZATION';
export const PROHIBITION = 'PROHIBITION';
export const REGISTRATION = 'REGISTRATION';
export const SHOW_PASSWORD = 'SHOW_PASSWORD';
export const SHOW_PASSWORD2 = 'SHOW_PASSWORD2';
