export const AUTHORIZATION = 'AUTHORIZATION';
export const PROHIBITION = 'PROHIBITION';
export const REGISTRATION = 'REGISTRATION';
export const GET_LOCATION ='GET_LOCATION';
export const GET_COURSE ='GET_COURSE';
export const BET_WIN ='BET_WIN';
export const BET_LOSE ='BET_LOSE';
export const CLOSE_CONGRATULATION ='CLOSE_CONGRATULATION';
